# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    # Directory\:
    #     resource: '../src/*'
    #     exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    # Directory\Controller\:
    #     resource: '../src/Controller'
    #     tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    # Commands
    Directory\UI\Command\:
        resource: './../../../../src/UI/Command/*'

    # Controllers
    Directory\UI\Controller\:
        resource: './../../../../src/UI/Controller/*/*Controller.php'
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']

    # Exception Handler
    Directory\UI\Controller\RequestExceptionHandler: ~

    # Command Bus
    Directory\Application\Command\CommandBus:
        alias: 'Directory\Infrastructure\Messenger\MessengerCommandBus'
    Directory\Infrastructure\Messenger\MessengerCommandBus:
        arguments:
            - '@command.bus'

    Directory\Application\Command\:
        resource: './../../../../src/Application/Command/*/*Handler.php'
        tags: [{ name: messenger.message_handler, bus: command.bus }]

    ## Query Bus
    Directory\Application\Query\QueryBus:
        alias: 'Directory\Infrastructure\Messenger\MessengerQueryBus'
    Directory\Infrastructure\Messenger\MessengerQueryBus:
        arguments:
            - '@query.bus'

    Directory\Application\Query\:
        resource: './../../../../src/Application/Query/*/*Handler.php'
        tags: [{ name: messenger.message_handler, bus: query.bus }]

    ## Middleware
    Directory\Infrastructure\Messenger\ApplicationExceptionMiddleware: ~

    ## Doctrine Connection
    Doctrine\DBAL\Connection:
        factory: [ 'Directory\Infrastructure\Doctrine\ConnectionFactory', 'buildConnection']
        arguments:
            - '%env(resolve:DOCTRINE_URL)%'

    ## User Repository
    Directory\Domain\User\UserRepository:
        alias: 'Directory\Infrastructure\Doctrine\Repository\DoctrineUserRepository'
    Directory\Infrastructure\Doctrine\Repository\DoctrineUserRepository: ~


    # Doctrine Migration tools
    Doctrine\Migrations\Provider\SchemaProviderInterface:
        alias: 'Directory\Infrastructure\Doctrine\Schema\SchemaProvider'
    Directory\Infrastructure\Doctrine\Schema\SchemaProvider: ~

    Doctrine\Migrations\Configuration\Configuration:
        arguments:
            - '@Doctrine\DBAL\Connection'
        calls:
            - ['setMigrationsNamespace', ['Directory\Infrastructure\Doctrine\Migration']]
            - ['setMigrationsDirectory', ['%kernel.project_dir%/src/Infrastructure/Doctrine/Migration']]

    Doctrine\Migrations\Tools\Console\Command\:
        resource: './../../../../vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command'
        calls:
            - [ setConnection, [ '@Doctrine\DBAL\Connection']]
            - [ setMigrationConfiguration, [ '@Doctrine\Migrations\Configuration\Configuration']]
